project:
  type: website

website:
  title: "Sophie Nguyen"
  navbar:
    left:
      - href: https://sophie-huongnguyen.github.io/
        text: Home
      - href: https://sophie-huongnguyen.github.io/productivity/intro.html
        text: Productivity
      - href: https://sophie-huongnguyen.github.io/projects/intro.html
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

